### ISSUE TITLE
amazing! but,how to turn the shaking off?

### ISSUE THREAD

**Issue by vopjie** [codeinthedark/editor#12]
it's uncomfortable

**Comment by JijinJayakumar** [comment]
Just disable the shake elements/functions in Javascript with comment tag // 


im using [Brackets](https://github.com/Equals182/brackets-power-mode) , 
for bracket users who want to turn of the screen shaking in power mode, 
Open extension folder
find powermode _**equals182.brackets-power-mode**_ plugin folder
edit **main.js**

find
`preferences.definePreference("screenShake.enabled", "boolean", true);
 preferences.definePreference("screenShake.minIntensity", "integer", 1);
 preferences.definePreference("screenShake.maxIntensity", "integer", 3);`

and disable it

`
//preferences.definePreference("screenShake.enabled", "boolean", true);
    //preferences.definePreference("screenShake.minIntensity", "integer", 1);
    //preferences.definePreference("screenShake.maxIntensity", "integer", 3);
`
