### ISSUE TITLE
Time Remaining Countdown

### ISSUE THREAD

**Issue by sHesl** [codeinthedark/editor#5]
I've added a time remaining counter to my fork which is started on the first keystroke. Is this something worth incorporating into master? Could also be set up to disable text entry after the timer has ran down. Power mode can also be permanently enabled for the last minute/s. 

In my fork I replaced the streak counter with a countdown, but both could be visible, or maybe toggled via a config setting?

Thoughts?

![image](https://cloud.githubusercontent.com/assets/12849568/11473379/f3254794-9769-11e5-93df-fd6797f431c9.png)

**Comment by JoelBesada** [comment]
Sorry for not replying! This is a cool idea but I think it's a bit tricky to have it be completely in sync with all the contestants. We generally have the time remaining projected on a wall somewhere where everyone can see it, to make sure everyone are clear on how much time there is left.
